### ISSUE TITLE
Non required fields causing failed import

### ISSUE THREAD

**Issue by bryanwillis** [CharbelNemnom/Power-MVP-Elite#3]
When importing from CSV if the user is missing any "Non Required fields" it throws back a bad request and doesn't import the user.

Here's part of the error:
`Message: Invalid value specified for for property 'telephoneNumber' of resource 'user'`

What is the best way to import users if they have empty spaces in certain CSV columns? The required fields check is good because it skips to the next record, but for non-required such as telephone we would like it to still import the user and just skip that specific field. Any suggestion??

Thanks!

**Comment by CharbelNemnom** [comment]
Hello Bryan,

Thanks for the question.

Could you put $null where there is no value in that field?

E.g. Replace (,,) with comma $null comma (,$null,)
