### ISSUE TITLE
Multi-Factor authentication issue

### ISSUE THREAD

**Issue by klem-ent** [CharbelNemnom/Power-MVP-Elite#6]
Hello,

Actually it give you an error like: " Cannot connect to Azure AD. Please check your credentials. Exiting!" if you are launching the script with an account with MFA enabled.

Edit: I workedarround this by setting the credential parameter to Mandatory=$false & adding the MFA option:
```
    [Parameter(Position=1, Mandatory=$false, HelpMessage='Specify Credentials')]
    [Alias('Cred')]
    [PSCredential]$Credential,
# Use MFA login
    [Switch]$MFA

if ( $MFA ) {
    Connect-AzureAD -ErrorAction Stop | Out-Null
	} Else{
		Connect-AzureAD -Credential $Credential -ErrorAction Stop | Out-Null
		}

```

**Comment by CharbelNemnom** [comment]
Thank you for the note!

I will update the script.
